/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rafael' at '2/26/17 9:13 PM' with Gradle 3.0
 *
 * @author rafael, @date 2/26/17 9:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
